### ISSUE TITLE
Why force bounds to be integers when the variable type is an integer?

### ISSUE THREAD

**Issue by jlerman44** [biosustain/optlang#117]
This seems like a perfectly valid problem setup:

Maximize x 
subject to:
x<= 3.5
x must be integer

Of course the solution is 3... but optlang will tell you it is not a valid setup. perhaps this should be changed to a warning?

Best,
Josh

**Comment by KristianJensen** [comment]
Hi. I agree that there is nothing conceptually wrong with the problem you have written. I'm not sure how all the solvers will react to non-integer bound to integer variables. I will look into this and possibly push a change to allow non-integer bounds.

**Comment by jlerman44** [comment]
Thanks ! The software is super nice. I have been doing a few tutorials and
folks really love it !

Josh

**Comment by KristianJensen** [comment]
Thanks! I'm happy to hear that people find it useful :)

GLPK complains about non-integer bounds on integer variables and doesn't optimize the problem (cplex and gurobi have no problems with it). To have as similar interfaces as possible for the different solvers I'm going to keep behaviour as it is for now.

The problem you have written can still be formulated by using a constraint instead of a bound for the `x <= 3.5` condition.
