### ISSUE TITLE
Add QP support for gurobi interface

### ISSUE THREAD

**Issue by KristianJensen** [biosustain/optlang#148]
This should not take a huge effort as the necessary logic is implemented in `expression_parsing.py`

**Comment by cdiener** [comment]
Is somebody actively working on that? Otherwise I would give it a shot since cplex QPs are pretty slow for me and I would try something else...

**Comment by KristianJensen** [comment]
Nobody else is working on that as far as I'm aware. However Moritz is currently working on refactoring large parts of the codebase, so depending on the progress of that, it might be better to wait until its's done (or what do you think @Midnighter ?).

**Comment by Midnighter** [comment]
It depends a little on how urgently you need it Christian. My refactor will still take 2-4 weeks (I'm not sure yet that I can complete it next sprint since memote needs a lot of attention right now). Currently, the goal is to come out of the refactor with a working GLPK interface. All other solvers will need to be refactored as well. In my opinion they should be a lot easier to implement, though.

So while it may not be the best use of your time right now it's also not the worst. Then you have it for sure and the QP capability can also be more easily added to the refactored optlang.

**Comment by cdiener** [comment]
Maybe @KristianJensen knows more about it but I think the only thing required to make that work in gurobi would be adding the respective code to `gurobi_interface.Objective` and maybe some adjustments to to `Model`. That should, in theory, not interfere with the refactor, or would it?

**Comment by KristianJensen** [comment]
Yes it should mainly require changes to Objective and Model.objective.setter, and it should be pretty straightforward to move your additions to the refactored code. So I say go for it :)

**Comment by cdiener** [comment]
Honestly, I wan not planning to get on it immediately but will probably play around with it soon. Already alleviated my cplex problems a bit by changing the default QP method which does not play well with large problems....

**Comment by KristianJensen** [comment]
@cdiener You might know this already, but another trick to making QP's faster is to diagonalize Q, e.g. by adding some aux variables (if it's not diagonal already)

**Comment by cdiener** [comment]
@KristianJensen already switched to an almost diagonal problem formulation. My major problem was that the primal method is the fastest for QPs but does often give me infeasible errors even though my problem always includes the full zero solution as feasible one (so there is always a feasible solution).

**Comment by Midnighter** [comment]
Is this issue now done with merging of #149?
