### ISSUE TITLE
Overflow exception

### ISSUE THREAD

**Issue by layderv** [biosustain/optlang#165]
Depending on the value of `k`, the following code produces `OverflowError: Python int too large to convert to C long`.

```
from __future__ import print_function
from optlang import Model, Variable, Constraint, Objective

k = 1000000000000000000000000
p = Variable('p')
p.ub = k
p.lb = -p.ub

c1 = Constraint(p + 10, ub=100)
c2 = Constraint(p - 10, lb=1e-8)
obj = Objective(p, direction='min')

model = Model(name='model')
model.objective = obj
model.add([c1, c2])

status = model.optimize()

print("status:", model.status)
print("objective value:", model.objective.value)
for var_name, var in model.variables.iteritems():
    print(var_name, "=", var.primal)
```

**Comment by KristianJensen** [comment]
Thanks for the report. Which solver are you using?

**Comment by Midnighter** [comment]
If you want infinite bounds (or the maximum value depending on the solver) you can simply assign `None` or `numpy.inf`.

**Comment by layderv** [comment]
Hi @KristianJensen, the solver is _cplex_. The error is in `array = CPX.double_list_to_C_array(seq)` (line 92 in _cplex/\_internal/\_list\_array\_utils.py_). 
Do you need the full stack trace?
@Midnighter thanks for the suggestion!

**Comment by phantomas1234** [comment]
Regarding these issues, I am never sure if is optlang supposed to guard against those (and how one would do that)? I mean this is the CPLEX Python API crapping out in the end of day, right?.

**Comment by layderv** [comment]
@phantomas1234 I'm happy to report this issue somewhere else, if more appropriate

**Comment by KristianJensen** [comment]
For some reason this error only occurs when the bound is set before adding the variable to the problem. The exception can be avoided by converting the number to float instead of int, however then a large bound is just converted to zero it seems.

I agree that cases like this can probably not always be fixed in optlang, since it has to do with how each individual solver encodes bounds etc.

If what you want to achieve is a variable that is effectively unbounded, you should set the bound to None, as Midnighter suggested. If you really have problems with numbers of that magnitude, it would probably be good to scale everything down.

@layderv Can this solve your problem?

**Comment by KristianJensen** [comment]
@layderv I agree that ideally there should be no upper limit to bounds, coefficients etc, but unfortunately the problem stems from how each individual underlying solver (glpk, cplex etc) handles numbers.

As it currently stands the user has a possible value range of at least 25 orders of magnitude (1e-9 to > 1e16). If this is not sufficient to formulate a given problem I think there would be other issues with solving it as well (the solvers generally don't like ill-conditioned problems).

I'll close this issue and open a separate one for implementing better warnings/errors if the numerical limits are exceeded.
