### ISSUE TITLE
Getting primals from unsolved or infeasible models

### ISSUE THREAD

**Issue by cdiener** [biosustain/optlang#64]
Currently, `_round_primal_to_bounds` (called by `.primal_values` in some interfaces) throws an error if the primal values lie outside the bounds. However, that only makes sense for 'optimal' solutions. If the solver declared the solution as 'infeasible' that means by definition that one of the primal values violates a constraint (equality or inequality) so it is "ok" for infeasible solutions to lie outside of the bounds and no error should be thrown in that case.

Also creates quite a headache for cobrapy code since the Solution object is created regardless of the solver status and thus throws errors for infeasible solutions.

**Comment by KristianJensen** [comment]
Hi Christian

This behaviour is actually somewhat intended. Primal values are only defined if an optimal (or feasible at least) solution can be found, otherwise they can be anything. Thus primal values are only supposed to be retrieved after optimising the model and assuring that it's optimal.

The way it fails at the moment is admittedly not very graceful (or consistent either) and I can see your point that it might be more convenient to return None instead of raising an exception. The issue is a bit more complicated though, since (as you also noted in the other issue) making changes to a model after optimising will also invalidate the previously found solution. The exact behaviour of this depends on the solver. Cplex will raise the exception you reported, while glpk will happily return values from the most recent solution. To avoid getting these errors (or getting numbers that are incorrect with regard to the current state of the model) optlang would have to monitor all changes to the model to determine whether a found solution is still valid, which in my opinion would not be worth the effort, overhead and added complexity. It would of course be possible to make `primal_values` return None if the model is infeasible, but this would only partially solve the problem.

Regarding cobrapy, can't it just check the solution status after optimizing and only retrieve the primal values if it's optimal?

**Comment by KristianJensen** [comment]
I've renamed this issue to the more general problem of handling primals when an optimal solution doesn't exist

**Comment by cdiener** [comment]
Hm, mathematically speaking primal values are always defined, even though they might not be optimal and non-unique.  

The reason why many solvers such as cplex, GLPK, gurobi and others allow retrieving primal values for infeasible solutions is that you can easily check which variable/constraint causes the infeasibility. This is impossible with optlang at the moment. At least for cobrapy it would be helpful if optlang would allow retrieval of those infeasible values maybe by setting an option, otherwise we would have to get the values from the lower level APIs which defeats the point of using optlang.

**Comment by KristianJensen** [comment]
Ah ok, I didn't realize you wanted to actually use the infeasible primals. In that case I'll just disable the _round_primal_to_bounds for non-optimal solutions like you suggested :)
Sorry for misunderstanding you.

**Comment by cdiener** [comment]
Yes exactly! I completely agree with the invalidation under model changes or if the model never has been solved :)

Thanks for the fix! Makes things much easier for us!

**Comment by KristianJensen** [comment]
The change is in the devel branch now. It will get released at some point in the not so distant future

**Comment by cdiener** [comment]
Great. Thank :+1:

**Comment by cdiener** [comment]
Closing because it has been merged and released.
