### ISSUE TITLE
scipy interface gives inconsistent solutions

### ISSUE THREAD

**Issue by cdiener** [biosustain/optlang#67]
With appended model the scipy interface declares the problem as infeasible even if all other interfaces find the correct optimal solution (0.874).

### Reproduce:

[Download the model in JSON](http://storage.googleapis.com/cdiener/textbook.json)

```Python
import json
import optlang

with open("textbook.json") as f:
    m = optlang.scipy_interface.Model.from_json(json.load(f))

m.optimize()
```

**Comment by KristianJensen** [comment]
Hi

Thanks for the error report.
The problem is due to the scipy linprog function having a very small tolerance as default. The problem can't be solved by the function unless ALCD2x_reverse is allowed a value of ~1e-14.
I've added a tolerance option to scipy_interface.Model.configuration, and set the default value to 1e-9, which solves the problem.

Changing the tolerance to another value can be done by e.g. `model.configuration.tolerance = 1e-6`.

**Comment by cdiener** [comment]
Thanks for the fix!

**Comment by cdiener** [comment]
Closing because it has been merged and released.
